### PR TITLE
Resolved issue 29

### LINKED ISSUE #29: When entering a CRN that does not exist, it is unclear that the course was not found.
Entering in an invalid CRN brings the user to an error page instead of notifying the user that the course does not exist. ([https://schedules.gmu.edu/search?query=99999](https://schedules.gmu.edu/search?query=99999))

A quick fix could be to simply serve the user to a "no course found" page ([https://schedules.gmu.edu/search?query=ABC%20123](https://schedules.gmu.edu/search?query=ABC%20123)) but it could also suggest courses 'close' to the incorrect CRN ([https://schedules.gmu.edu/search?query=CS%2099](https://schedules.gmu.edu/search?query=CS%2099))

A similar problem is that this also happens whenever the query contains a 5-digit number ([https://schedules.gmu.edu/search?query=CS%2075005](https://schedules.gmu.edu/search?query=CS%2075005)) and while this is less likely than entering the wrong CRN, its a reasonable mistake for a user to make.

In any case, only telling the user "an error has occured" could lead to more attempts to enter the same query, which will result in the same error every time.

For those unfamiliar with the codebase (like me) I suggest starting in `app/controllers/search_controller.rb` and looking for the code block with `CourseSection.latest_by_crn`

### PR DESCRIPTION
**Pull request by Nicholas-Thor-Page**
Resolved #29 by only redirecting to the course page when a course with the specified CRN is found.

When a CRN is entered in the search, search_controller.rb used to ALWAYS send the user to the page for that course. If no course existed with that CRN, it would cause an error, as that page doesn't exist. The new behaviour only redirects to the course page when a course is actually found, otherwise it stays on the query page.

Additionally, the query page did not display a "No Results Found" message when the courses and instructors found were nil values, as it was previously impossible to reach that site with those variables holding nil values. But with the above fix, that is now possible, so now it checks to see if the courses or instructors are empty OR nil, and if they both are, it displays the "No results found" message.

### CODE REVIEW

File: schedules/app/controllers/search_controller.rb [hunk 1]
```diff
@@ -33,8 +33,10 @@ def index
 
     /[0-9]{5}/.match(params[:query]) do |m|
       course = CourseSection.latest_by_crn(m[0])
-      url = course_url(course.course) + "#section-" + course.id.to_s
-      redirect_to(url)
+      if not course.nil?
```
Comment (zacwood9) [inline schedules/app/controllers/search_controller.rb:36]: Minor code clarity nitpick: Ruby has an `unless` keyword that is equivalent to `if not`. Try using that here and moving the redirect into the unless statement!
